tls_defaults:
  green: 12
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # Extremos con 2 aproximaciones → alternancia simple
  A0:
    offset: 0
    phases:
      - active_approaches: ["A1A0"]   # Norte->Sur hacia A0
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0A0"]   # Oeste->Este hacia A0
        g: 12
        y: 3
        r: 1

  A1:
    offset: 2
    phases:
      - active_approaches: ["A0A1"]   # Sur->Norte hacia A1
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B1A1"]   # Oeste->Este hacia A1
        g: 12
        y: 3
        r: 1

  # Nodos de 3 brazos: E-W juntos, N-S solo
  B0:
    offset: 4
    compatibility_groups:
      - ["A0B0","C0B0"]   # Este<->Oeste simultáneos
      - ["B1B0"]          # Norte/SUR (solo)
    phases:
      - active_approaches: ["A0B0","C0B0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B1B0"]
        g: 12
        y: 3
        r: 1

  B1:
    offset: 6
    compatibility_groups:
      - ["A1B1","C1B1"]
      - ["B0B1"]
    phases:
      - active_approaches: ["A1B1","C1B1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0B1"]
        g: 12
        y: 3
        r: 1

  C0:
    offset: 8
    compatibility_groups:
      - ["B0C0","D0C0"]
      - ["C1C0"]
    phases:
      - active_approaches: ["B0C0","D0C0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C1C0"]
        g: 12
        y: 3
        r: 1

  C1:
    offset: 10
    compatibility_groups:
      - ["B1C1","D1C1"]
      - ["C0C1"]
    phases:
      - active_approaches: ["B1C1","D1C1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C0C1"]
        g: 12
        y: 3
        r: 1

  D0:
    offset: 12
    compatibility_groups:
      - ["C0D0","E0D0"]
      - ["D1D0"]
    phases:
      - active_approaches: ["C0D0","E0D0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["D1D0"]
        g: 12
        y: 3
        r: 1

  D1:
    offset: 14
    compatibility_groups:
      - ["C1D1","E1D1"]
      - ["D0D1"]
    phases:
      - active_approaches: ["C1D1","E1D1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["D0D1"]
        g: 12
        y: 3
        r: 1

  E0:
    offset: 16
    compatibility_groups:
      - ["D0E0","F0E0"]
      - ["E1E0"]
    phases:
      - active_approaches: ["D0E0","F0E0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["E1E0"]
        g: 12
        y: 3
        r: 1

  E1:
    offset: 18
    compatibility_groups:
      - ["D1E1","F1E1"]
      - ["E0E1"]
    phases:
      - active_approaches: ["D1E1","F1E1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["E0E1"]
        g: 12
        y: 3
        r: 1

  # Extremos derechos (2 aproximaciones)
  F0:
    offset: 20
    phases:
      - active_approaches: ["E0F0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["F1F0"]
        g: 12
        y: 3
        r: 1

  F1:
    offset: 22
    phases:
      - active_approaches: ["E1F1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["F0F1"]
        g: 12
        y: 3
        r: 1
