tls_defaults:
  green: 14
  yellow: 3
  red: 2
  offset: 0
  min_green: 5
  max_green: 70
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # Nodo central superior (fila A, col 3 aprox.)
  A3:
    offset: 4
    compatibility_groups:
      - ["A2A3","A4A3"]   # E–O simultáneo en la arteria
    phases:
      - active_approaches: ["A2A3","A4A3"]   # E–O
        g: 18
        y: 3
        r: 2
      - active_approaches: ["B3A3"]          # S→N (vertical, único carril entrante)
        g: 10
        y: 3
        r: 2

  # Nodo central inferior (fila B, col 3)
  B3:
    offset: 6
    compatibility_groups:
      - ["B2B3","B4B3"]   # E–O simultáneo
    phases:
      - active_approaches: ["B2B3","B4B3"]
        g: 18
        y: 3
        r: 2
      - active_approaches: ["A3B3"]          # N→S
        g: 10
        y: 3
        r: 2
  # Los demás cruces usan el fallback (una vía a la vez)
