# ---------------------------------------------
# configs/scenarios/corridor_3x2.yaml
# Baseline: 1 aproximación activa por fase.
# Offsets escalonados para progresión horizontal:
#   fila 0: A0 (0s) -> B0 (6s) -> C0 (12s)
#   fila 1: A1 (3s) -> B1 (9s) -> C1 (15s)
# ---------------------------------------------

tls_defaults:
  green: 12
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # ---- Fila superior (row 0) ----
  A0:
    offset: 0
    # incoming: A1A0, B0A0
    phases:
      - active_approaches: ["A1A0"]   # norte->A0 (o arriba->abajo, según tu orientación)
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0A0"]   # oeste->A0 (o izquierda->derecha)
        g: 12
        y: 3
        r: 1

  B0:
    offset: 6
    # incoming: A0B0, B1B0, C0B0
    phases:
      - active_approaches: ["A0B0"]   # oeste->B0
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B1B0"]   # sur->B0
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C0B0"]   # este->B0
        g: 12
        y: 3
        r: 1
    # Si más adelante quisieras pares compatibles (p.ej., E<->O), añade:
    # compatibility_groups:
    #   - ["A0B0","C0B0"]

  C0:
    offset: 12
    # incoming: B0C0, C1C0
    phases:
      - active_approaches: ["B0C0"]   # oeste->C0
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C1C0"]   # norte/sur->C0 (según topología)
        g: 12
        y: 3
        r: 1

  # ---- Fila inferior (row 1) ----
  A1:
    offset: 3
    # incoming: A0A1, B1A1
    phases:
      - active_approaches: ["A0A1"]   # norte/sur->A1
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B1A1"]   # este/oeste->A1
        g: 12
        y: 3
        r: 1

  B1:
    offset: 9
    # incoming: A1B1, B0B1, C1B1
    phases:
      - active_approaches: ["A1B1"]   # oeste->B1
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0B1"]   # norte->B1
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C1B1"]   # este->B1
        g: 12
        y: 3
        r: 1
    # Opcional futuro:
    # compatibility_groups:
    #   - ["A1B1","C1B1"]

  C1:
    offset: 15
    # incoming: B1C1, C0C1
    phases:
      - active_approaches: ["B1C1"]   # oeste->C1
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C0C1"]   # norte/sur->C1
        g: 12
        y: 3
        r: 1
