tls_defaults:
  green: 12
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # B1: opuestos B2B1 <-> B4B1; rama A1B1 aparte
  B1:
    offset: 0
    compatibility_groups:
      - ["B2B1", "B4B1"]
      - ["A1B1"]
    phases:
      - active_approaches: ["B2B1", "B4B1"]
        g: 14
        y: 3
        r: 2
      - active_approaches: ["A1B1"]
        g: 10
        y: 3
        r: 2

  # B2: opuestos B1B2 <-> B3B2; rama A1B2
  B2:
    offset: 3
    compatibility_groups:
      - ["B1B2", "B3B2"]
      - ["A1B2"]
    phases:
      - active_approaches: ["B1B2", "B3B2"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A1B2"]
        g: 8
        y: 3
        r: 1

  # B3: opuestos B2B3 <-> B4B3; rama A1B3
  B3:
    offset: 6
    compatibility_groups:
      - ["B2B3", "B4B3"]
      - ["A1B3"]
    phases:
      - active_approaches: ["B2B3", "B4B3"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A1B3"]
        g: 8
        y: 3
        r: 1

  # B4: opuestos B1B4 <-> B3B4; rama A1B4
  B4:
    offset: 9
    compatibility_groups:
      - ["B1B4", "B3B4"]
      - ["A1B4"]
    phases:
      - active_approaches: ["B1B4", "B3B4"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A1B4"]
        g: 8
        y: 3
        r: 1
