tls_defaults:
  green: 12
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # A0: incoming = A1A0, B0A0 → fases alternas (una vía a la vez)
  A0:
    offset: 0
    phases:
      - active_approaches: ["A1A0"]   # norte→A0 (según tu malla)
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0A0"]   # oeste→A0
        g: 12
        y: 3
        r: 1

  # A1: incoming = A0A1, B1A1
  A1:
    offset: 4
    phases:
      - active_approaches: ["A0A1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B1A1"]
        g: 12
        y: 3
        r: 1

  # B0: incoming = A0B0, B1B0
  B0:
    offset: 8
    phases:
      - active_approaches: ["A0B0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B1B0"]
        g: 12
        y: 3
        r: 1

  # B1: incoming = A1B1, B0B1
  B1:
    offset: 12
    phases:
      - active_approaches: ["A1B1"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0B1"]
        g: 12
        y: 3
        r: 1
