tls_defaults:
  green: 12
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # --- Fila A ---
  A0:
    # Incoming: A1A0, B0A0
    phases:
      - active_approaches: ["A1A0"]  # desde A1 -> A0
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B0A0"]  # desde B0 -> A0
        g: 12
        y: 3
        r: 1

  A1:
    # Incoming: A0A1, A2A1, B1A1
    # Compatibles: E<->O (A0A1 y A2A1) juntos; B1A1 solo
    offset: 4
    compatibility_groups:
      - ["A0A1", "A2A1"]
      - ["B1A1"]  # solo
    phases:
      - active_approaches: ["A0A1", "A2A1"]
        g: 14
        y: 3
        r: 2
      - active_approaches: ["B1A1"]
        g: 12
        y: 3
        r: 1

  A2:
    # Incoming: A1A2, B2A2
    phases:
      - active_approaches: ["A1A2"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["B2A2"]
        g: 12
        y: 3
        r: 1

  # --- Fila B ---
  B0:
    # Incoming: A0B0, B1B0, C0B0
    # Compatibles: N<->S (A0B0 y C0B0) juntos; B1B0 solo
    offset: 2
    compatibility_groups:
      - ["A0B0", "C0B0"]
      - ["B1B0"]
    phases:
      - active_approaches: ["A0B0", "C0B0"]
        g: 14
        y: 3
        r: 2
      - active_approaches: ["B1B0"]
        g: 12
        y: 3
        r: 1

  B1:
    # Incoming: A1B1, B0B1, B2B1, C1B1 (cruce 4 brazos)
    # Compatibles: N<->S y E<->O
    offset: 8
    compatibility_groups:
      - ["A1B1", "C1B1"]  # N<->S
      - ["B0B1", "B2B1"]  # O<->E
    phases:
      - active_approaches: ["A1B1", "C1B1"]
        g: 14
        y: 3
        r: 2
      - active_approaches: ["B0B1", "B2B1"]
        g: 14
        y: 3
        r: 2

  B2:
    # Incoming: A2B2, B1B2, C2B2
    # Compatibles: N<->S (A2B2 y C2B2); B1B2 solo
    offset: 4
    compatibility_groups:
      - ["A2B2", "C2B2"]
      - ["B1B2"]
    phases:
      - active_approaches: ["A2B2", "C2B2"]
        g: 14
        y: 3
        r: 2
      - active_approaches: ["B1B2"]
        g: 12
        y: 3
        r: 1

  # --- Fila C ---
  C0:
    # Incoming: B0C0, C1C0
    phases:
      - active_approaches: ["B0C0"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C1C0"]
        g: 12
        y: 3
        r: 1

  C1:
    # Incoming: B1C1, C0C1, C2C1
    # Compatibles: E<->O (C0C1 y C2C1); B1C1 solo
    offset: 6
    compatibility_groups:
      - ["C0C1", "C2C1"]
      - ["B1C1"]
    phases:
      - active_approaches: ["C0C1", "C2C1"]
        g: 14
        y: 3
        r: 2
      - active_approaches: ["B1C1"]
        g: 12
        y: 3
        r: 1

  C2:
    # Incoming: B2C2, C1C2
    phases:
      - active_approaches: ["B2C2"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["C1C2"]
        g: 12
        y: 3
        r: 1
