tls_defaults:
  green: 10
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 20
  max_cycle: 240

tls:
  # Pequeña “ola verde” vertical: offsets progresivos
  A0: { offset: 0,  compatibility_groups: [["B0A0","?"]] }     # '?' se ignora si no existe esa aproximación
  B0:
    offset: 3
    compatibility_groups:
      - ["A0B0","C0B0"]   # N<->S al mismo tiempo
    phases:
      - active_approaches: ["A0B0","C0B0"]
        g: 12
        y: 3
        r: 1

  C0:
    offset: 6
    compatibility_groups:
      - ["B0C0","D0C0"]
    phases:
      - active_approaches: ["B0C0","D0C0"]
        g: 12
        y: 3
        r: 1

  D0:
    offset: 9
    compatibility_groups:
      - ["C0D0","E0D0"]
    phases:
      - active_approaches: ["C0D0","E0D0"]
        g: 12
        y: 3
        r: 1
  # Resto: fallback por defecto
