tls_defaults:
  green: 12
  yellow: 3
  red: 1
  offset: 0
  min_green: 5
  max_green: 60
  min_yellow: 2
  max_yellow: 5
  min_red: 0
  max_red: 10
  min_cycle: 25
  max_cycle: 240

tls:
  # Ola verde a lo largo de la fila B (B0..B5) para tráfico este-oeste
  B0:
    offset: 0
    compatibility_groups:
      - ["A0B0","C0B0"]   # N–S
      - ["B1B0","B-1B0"]  # E–O (si existe el entrante WEST→B0; si no, omítelo)
    phases:
      - active_approaches: ["B1B0"]  # Este→Oeste (single si no hay opuesto)
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A0B0","C0B0"]
        g: 10
        y: 3
        r: 1

  B1:
    offset: 4
    compatibility_groups:
      - ["B0B1","B2B1"]
      - ["A1B1","C1B1"]
    phases:
      - active_approaches: ["B0B1","B2B1"]   # E–O
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A1B1","C1B1"]   # N–S
        g: 10
        y: 3
        r: 1

  B2:
    offset: 8
    compatibility_groups:
      - ["B1B2","B3B2"]
      - ["A2B2","C2B2"]
    phases:
      - active_approaches: ["B1B2","B3B2"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A2B2","C2B2"]
        g: 10
        y: 3
        r: 1

  B3:
    offset: 12
    compatibility_groups:
      - ["B2B3","B4B3"]
      - ["A3B3","C3B3"]
    phases:
      - active_approaches: ["B2B3","B4B3"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A3B3","C3B3"]
        g: 10
        y: 3
        r: 1

  B4:
    offset: 16
    compatibility_groups:
      - ["B3B4","B5B4"]
      - ["A4B4","C4B4"]
    phases:
      - active_approaches: ["B3B4","B5B4"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A4B4","C4B4"]
        g: 10
        y: 3
        r: 1

  B5:
    offset: 20
    compatibility_groups:
      - ["B4B5","B6B5"]
      - ["A5B5","C5B5"]
    phases:
      - active_approaches: ["B4B5","B6B5"]
        g: 12
        y: 3
        r: 1
      - active_approaches: ["A5B5","C5B5"]
        g: 10
        y: 3
        r: 1
  # Demás cruces: fallback con defaults
